version: '3'
networks:
    web:
        external: true
volumes:
    cache:
services:
    $SERVICE_NAME:
        image: "$CI_REGISTRY_IMAGE/app:$CI_COMMIT_BRANCH"
        container_name: "$SERVICE_NAME"
        networks:
            - web
        labels:
            - "traefik.http.routers.$SERVICE_NAME-app.rule=Host(`$SERVICE_DOMAIN`) || Host(`www.$SERVICE_DOMAIN`)"
            - "traefik.http.routers.$SERVICE_NAME-app.tls.certresolver=le"
            - "traefik.http.routers.$SERVICE_NAME-app.entrypoints=websecure"
            - "traefik.http.services.$SERVICE_NAME-app.loadbalancer.server.port=80"
            - "traefik.docker.network=web"
            - "traefik.enable=true"
        restart: "always"
        tty: yes
        stdin_open: true
